## Looking at DataFrame Data

In [1]:
import pandas as pd

In [2]:
file_path = "../../data/USCG.Search.Rescue.Stats.csv"
df = pd.read_csv(file_path)

### Heads/Tails

In [3]:
df.head() # Muestra las primeras filas del DataFrame para verificar que se ha cargado correctamente.

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1964,NaN,41525,NaN,2932,NaN,NaN,NaN,NaN,NaN
1965,NaN,38586,NaN,1984,NaN,NaN,NaN,NaN,NaN
1966,NaN,43366,NaN,2629,NaN,NaN,NaN,NaN,NaN
1967,NaN,42225,NaN,3028,NaN,NaN,NaN,NaN,NaN
1968,NaN,46922,NaN,2434,NaN,NaN,NaN,NaN,NaN

In [4]:
df.head(3) # Muestra las primeras 3 filas del DataFrame.

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1964,NaN,41525,NaN,2932,NaN,NaN,NaN,NaN,NaN
1965,NaN,38586,NaN,1984,NaN,NaN,NaN,NaN,NaN
1966,NaN,43366,NaN,2629,NaN,NaN,NaN,NaN,NaN

In [5]:
df.tail() # Muestra las últimas filas del DataFrame.

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
2011,20512.0,43954,21566.0,3793,259.0,476.0,735.0,392.0,NaN
2012,19787.0,43940,21609.0,4037,284.0,429.0,713.0,440.0,NaN
2013,17803.0,38272,19420.0,3753,226.0,425.0,651.0,252.0,NaN
2014,17508.0,38282,19032.0,3443,170.0,425.0,595.0,308.0,NaN
2015,16456.0,37215,18781.0,3536,169.0,434.0,603.0,330.0,NaN

In [6]:
df.tail(2) # Muestra las últimas 2 filas del DataFrame.

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
2014,17508.0,38282,19032.0,3443,170.0,425.0,595.0,308.0,NaN
2015,16456.0,37215,18781.0,3536,169.0,434.0,603.0,330.0,NaN

### Descriptive Statistics

In [7]:
df.describe() # Proporciona estadísticas descriptivas del DataFrame, como la media, la desviación estándar, etc.

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
count,46.000000,52.000000,46.000000,52.000000,46.000000,37.000000,46.000000,16.000000,0.0
mean,46296.608696,58013.769231,67666.586957,4339.230769,670.956522,508.486486,1079.956522,468.000000,NaN
std,17438.646933,13480.714228,29300.537271,1334.134847,499.839128,134.761028,394.869765,149.916866,NaN
min,16456.000000,37215.000000,18781.000000,1984.000000,169.000000,180.000000,533.000000,252.000000,NaN
25%,31676.250000,46632.750000,33202.750000,3348.500000,281.750000,425.000000,751.000000,336.750000,NaN
50%,50621.500000,55945.500000,81711.500000,4221.000000,383.500000,492.000000,998.000000,437.500000,NaN
75%,57072.750000,69049.750000,88433.750000,5484.500000,1118.750000,593.000000,1440.750000,584.250000,NaN
max,77954.000000,86222.000000,110267.000000,7889.000000,1783.000000,800.000000,1821.000000,732.000000,NaN

In [8]:
df.min() # Muestra el valor mínimo de cada columna numérica del DataFrame.

Fiscal Year                          16456.0
Cases                                37215.0
Responses                            18781.0
Sorties                               1984.0
Lives Saved                            169.0
Lives Lost After CG Notification       180.0
Lives Lost Before CG Notification      533.0
Total                                  252.0
Lives Unaccounted For                    NaN
dtype: float64

In [9]:
df.std() # Muestra la desviación estándar de cada columna numérica del DataFrame.

Fiscal Year                          17438.646933
Cases                                13480.714228
Responses                            29300.537271
Sorties                               1334.134847
Lives Saved                            499.839128
Lives Lost After CG Notification       134.761028
Lives Lost Before CG Notification      394.869765
Total                                  149.916866
Lives Unaccounted For                         NaN
dtype: float64

### Selecting Columns

In [10]:
df.columns # Muestra los nombres de las columnas del DataFrame.

Index(['Fiscal Year', 'Cases', 'Responses', 'Sorties', 'Lives Saved',
       'Lives Lost After CG Notification', 'Lives Lost Before CG Notification',
       'Total', 'Lives Unaccounted For '],
      dtype='str')

In [11]:
df['Cases'] # Muestra la columna 'Cases' del DataFrame.

1964    41525
1965    38586
1966    43366
1967    42225
1968    46922
1969    48720
1970    52183
1971    56181
1972    60328
1973    64182
1974    67692
1975    70551
1976    75069
1977    82601
1978    86222
1979    79858
1980    81476
1981    78951
1982    75717
1983    72585
1984    66073
1985    70237
1986    68805
1987    66656
1988    63446
1989    64027
1990    64971
1991    66409
1992    69856
1993    69784
1994    70337
1995    63679
1996    55710
1997    52141
1998    46602
1999    50622
2000    48226
2001    49502
2002    46643
2003    51389
2004    59995
2005    52741
2006    45910
2007    47517
2008    44931
2009    47497
2010    46407
2011    43954
2012    43940
2013    38272
2014    38282
2015    37215
Name: Cases, dtype: int64

In [14]:
df[["Sorties", "Cases"]] # Muestra las columnas 'Sorties' y 'Cases' del DataFrame.

      Sorties  Cases
1964     2932  41525
1965     1984  38586
1966     2629  43366
1967     3028  42225
1968     2434  46922
1969     2050  48720
1970     4135  52183
1971     2423  56181
1972     2633  60328
1973     2918  64182
1974     2751  67692
1975     3024  70551
1976     2995  75069
1977     4121  82601
1978     4386  86222
1979     5747  79858
1980     6868  81476
1981     6339  78951
1982     5675  75717
1983     5946  72585
1984     5645  66073
1985     6497  70237
1986     4307  68805
1987     5785  66656
1988     4307  63446
1989     3981  64027
1990     4407  64971
1991     5465  66409
1992     5543  69856
1993     5826  69784
1994     7889  70337
1995     4453  63679
1996     5047  55710
1997     3897  52141
1998     3194  46602
1999     3743  50622
2000     3400  48226
2001     4010  49502
2002     3661  46643
2003     5192  51389
2004     5557  59995
2005     5635  52741
2006     5275  45910
2007     5200  47517
2008     4900  44931
2009     4882  47497
2010     4362  46407
2011     3793  43954
2012     4037  43940
2013     3753  38272
2014     3443  38282
2015     3536  37215

In [15]:
df.Sorties # Otra forma de mostrar la columna 'Sorties' del DataFrame.

1964    2932
1965    1984
1966    2629
1967    3028
1968    2434
1969    2050
1970    4135
1971    2423
1972    2633
1973    2918
1974    2751
1975    3024
1976    2995
1977    4121
1978    4386
1979    5747
1980    6868
1981    6339
1982    5675
1983    5946
1984    5645
1985    6497
1986    4307
1987    5785
1988    4307
1989    3981
1990    4407
1991    5465
1992    5543
1993    5826
1994    7889
1995    4453
1996    5047
1997    3897
1998    3194
1999    3743
2000    3400
2001    4010
2002    3661
2003    5192
2004    5557
2005    5635
2006    5275
2007    5200
2008    4900
2009    4882
2010    4362
2011    3793
2012    4037
2013    3753
2014    3443
2015    3536
Name: Sorties, dtype: int64

### Selecting Columns and Rows

In [16]:
df.iloc[3] # Muestra la fila en la posición 3 del DataFrame (indexada desde 0).

Fiscal Year                              NaN
Cases                                42225.0
Responses                                NaN
Sorties                               3028.0
Lives Saved                              NaN
Lives Lost After CG Notification         NaN
Lives Lost Before CG Notification        NaN
Total                                    NaN
Lives Unaccounted For                    NaN
Name: 1967, dtype: float64

In [17]:
df.iloc[3:29] # Muestra las filas desde la posición 3 hasta la 28 del DataFrame (indexada desde 0).

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1967,NaN,42225,NaN,3028,NaN,NaN,NaN,NaN,NaN
1968,NaN,46922,NaN,2434,NaN,NaN,NaN,NaN,NaN
1969,NaN,48720,NaN,2050,NaN,NaN,NaN,NaN,NaN
1970,44975.0,52183,62286.0,4135,1783.0,NaN,1783.0,NaN,NaN
1971,48894.0,56181,68251.0,2423,1324.0,NaN,1324.0,NaN,NaN
1972,51539.0,60328,72306.0,2633,1389.0,NaN,1389.0,NaN,NaN
1973,55107.0,64182,77209.0,2918,1474.0,NaN,1474.0,NaN,NaN
1974,59335.0,67692,79950.0,2751,1509.0,NaN,1509.0,NaN,NaN
1975,62334.0,70551,81561.0,3024,1254.0,NaN,1254.0,NaN,NaN
1976,67179.0,75069,87807.0,2995,1112.0,NaN,1112.0,NaN,NaN
1977,74637.0,82601,96021.0,4121,1458.0,NaN,1458.0,NaN,NaN
1978,77954.0,86222,100262.0,4386,1556.0,NaN,1556.0,NaN,NaN
1979,72517.0,79858,92117.0,5747,949.0,672.0,1621.0,NaN,NaN
1980,73345.0,81476,93726.0,6868,1235.0,586.0,1821.0,NaN,NaN
1981,71781.0,78951,91432.0,6339,1080.0,637.0,1717.0,NaN,NaN
1982,68552.0,75717,87715.0,5675,1359.0,446.0,1805.0,NaN,NaN
1983,63980.0,72585,85796.0,5946,1121.0,640.0,1761.0,NaN,NaN
1984,57431.0,66073,80698.0,5645,1148.0,319.0,1467.0,NaN,NaN
1985,60775.0,70237,88449.0,6497,1076.0,259.0,1335.0,NaN,NaN
1986,51765.0,68805,89318.0,4307,475.0,180.0,655.0,NaN,NaN
1987,55998.0,66656,87211.0,5785,1015.0,576.0,1591.0,NaN,NaN
1988,54199.0,63446,83616.0,4307,583.0,449.0,1032.0,NaN,NaN
1989,52776.0,64027,81862.0,3981,461.0,646.0,1107.0,NaN,NaN
1990,53097.0,64971,84033.0,4407,463.0,622.0,1085.0,NaN,NaN
1991,52782.0,66409,84872.0,5465,368.0,748.0,1116.0,NaN,NaN
1992,53294.0,69856,88388.0,5543,399.0,540.0,939.0,NaN,NaN

In [20]:
df.iloc[3:29,3] # Muestra los valores de la columna en la posición 3 (indexada desde 0) para las filas desde la posición 3 hasta la 28 del DataFrame.

1967    3028
1968    2434
1969    2050
1970    4135
1971    2423
1972    2633
1973    2918
1974    2751
1975    3024
1976    2995
1977    4121
1978    4386
1979    5747
1980    6868
1981    6339
1982    5675
1983    5946
1984    5645
1985    6497
1986    4307
1987    5785
1988    4307
1989    3981
1990    4407
1991    5465
1992    5543
Name: Sorties, dtype: int64

In [21]:
df.head()

,Fiscal Year,Cases,Responses,Sorties,Lives Saved,Lives Lost After CG Notification,Lives Lost Before CG Notification,Total,Lives Unaccounted For
1964,NaN,41525,NaN,2932,NaN,NaN,NaN,NaN,NaN
1965,NaN,38586,NaN,1984,NaN,NaN,NaN,NaN,NaN
1966,NaN,43366,NaN,2629,NaN,NaN,NaN,NaN,NaN
1967,NaN,42225,NaN,3028,NaN,NaN,NaN,NaN,NaN
1968,NaN,46922,NaN,2434,NaN,NaN,NaN,NaN,NaN

In [27]:
df.loc[1965:1974, ["Cases", "Sorties"]] # Muestra los valores de las columnas 'Cases' y 'Sorties' para las filas con índices desde 1965 hasta 1974 del DataFrame.

      Cases  Sorties
1965  38586     1984
1966  43366     2629
1967  42225     3028
1968  46922     2434
1969  48720     2050
1970  52183     4135
1971  56181     2423
1972  60328     2633
1973  64182     2918
1974  67692     2751